version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile

    ports:
      - "3333:3000"
    networks:
      - net
    depends_on:
      - rabbitmq
      - order

  order:
    container_name: order
    build:
      context: .
      dockerfile: ./order/Dockerfile
    networks:
      - net
    depends_on:
      - rabbitmq
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net

networks:
  net:
    driver: bridge
